language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: huQORfUkWyAicvOpyyGBxG/KMAsc/pZe7UIu7dRS1Iw3mJRHJsShnOgiCE8gfndayw7miiTTbR/cmYhDiXX+clpvwDC7GFyn4IqaN61W8FsprxqiDXAzzAuAEWfNct3pJv+5GjDX4XWyFQiTn3rwR+144XYrYd+GLS45DDPQ8Qc=
  on:
    tags: true
    branches: true
